### PR TITLE
fix: eslint improvement

### PR DESCRIPTION
**Pull request by paschalidi**
Adds `'plugin:prettier/recommended'` in the list. This will make eslint recognise errors when our jsx is not formatted right as it should have done here for example https://github.com/small-ads/core/pull/67/commits/5f8660c4807945842b0c4dc03e15b6481cd5ca99#diff-746224c245c31b8e0092392bf7c22c55cc0779a84be1f9ab6715d35c3f77a7ebR16

### CODE REVIEW

**Comment by AdrianValdes** [comment]
Oh, that happened because I just added a line using GitKraken, so when I add a hunk that could change the format, I have to keep that in mind. Sorry.

**Comment by AdrianValdes** [comment]
Why is the linter complaining about  `error  Replace `"@testing-library/jest-dom"` with `'@testing-library/jest-dom'`  prettier/prettier`
I don't get it, we have single quotes there.

**Comment by paschalidi** [comment]
@AdrianValdes check this out

**Comment by AdrianValdes** [comment]
So we are going to have double quotes for the components properties `<button type="button" onClick={handleSignIn}>` now? I am just asking because that was the behavior I had locally and I had to add a .prettierrc to modify it so I want to know if I have to delete it.

**Comment by paschalidi** [comment]
I think this is the intended behaviour of the linter however because we werent having this plugin on the linter wasnt catching it.

What are the issues you are seeing?

**Comment by AdrianValdes** [comment]
> What are the issues you are seeing?
No problem, all good, I wanted to know if we wanted this behavior. I had that behavior before, maybe you remember I was making some PRs with the double-quotes there. I had to fight against it creating a separated `.pretterrc`, but no problem, I will delete it and I think I will have this behavior back.

**Comment by paschalidi** [comment]
Can you make a review when you have the time

**Review by AdrianValdes — APPROVED** [review]
Thanks for the change. It is going to keep the code clean

**Pull request merged**
