### PR TITLE
fix: error on linter

### PR DESCRIPTION
**Pull request by AdrianValdes**
hi @paschalidi, 
I made clean pull from main and I started to have errors with the `linter`. Very weird because I had try to solution locally before and it didn't complain. To solve it on my side I first delete all the `node_modules` and the `package-lock.json` and re-install the project again, but that didn't solve it. 

I had to configure my `parserOptions` on my `.eslintrc.js` like this:

```
 parserOptions: {
    project: './tsconfig.json',
    tsconfigRootDir: __dirname,
  },
```

I have been reading about this issue and apparently there are discrepancies between `yarn` and `npm` for this case, but I though because we are using `lerna` that wouldn't matter :thinking:. 

Could you try this solution locally? It is a bit different to what I had before that was giving you trouble.

### CODE REVIEW

**Comment by AdrianValdes** [comment]
BTW, the re-install changed some versions of the in the `package-lock.json` I don't know if that has something to do with this issue we are having.

**Comment by paschalidi** [comment]
Can we start using yarn?

**Comment by paschalidi** [comment]
Usually it isnt the best practise to delete those package.json.lock files. But I see where you coming from

**Comment by AdrianValdes** [comment]
> Can we start using yarn?

Sure we can, if you think that is good, by all means. I can install it and start using it.

**Comment by AdrianValdes** [comment]
> Usually it isnt the best practise to delete those package.json.lock files. But I see where you coming from

Oh, didn't know that. One time you told me to do it to solve one issue we were having with Github Actions and I thought something similar could be happening. I am going to read about `package-lock.json` files and why to treat them with care.

**Comment by paschalidi** [comment]
Hm let me think for a second. I dont like that we are deleting those package.lock.json files so often. 

Perhaps we dont have to use yarn but can you explain why we need to delete the package.lock.json here? 
I reckon this is really last resort..

**Comment by AdrianValdes** [comment]
I didn't know it was a last resort procedure. I thought it was a way of "cleaning" the installs and overriding "errors" there could be. I won't do it again. I will read about how they work as soon as I am back from the groceries.

**Comment by AdrianValdes** [comment]
I am also going to:
1. Install yarn.
2. Clone to repository in a new file.
3. Install it using yarn.

Is that the correct procedure, or am I missing something? There is something I should pay attention to or read?

**Comment by paschalidi** [comment]
We dont really need to use yarn to be honest, but yeah lets give it a shot. 

Lets do it in this current PR. 
1. Install yarn globally.
2. remove all the package.lock.json.
3. configure lerna to use yarn
4. run `yarn` to isntall deps
5. run `lerna bootstrap` to install deps in the projects

**Comment by AdrianValdes** [comment]
hi @paschalidi,
Finally done. I ran into a few problems, I had to downgrade the version of Node, if not I would get errors when doing the bootstrapping. Anyhow, it works now without errors locally. Could you check if it works on your side?

**Comment by AdrianValdes** [comment]
hi @paschalidi , I have some doubts regarding this topic. From now on we should install everything using `yarn add <packageName>` is that right?

**Comment by paschalidi** [comment]
right

**Review by paschalidi — APPROVED** [review]
:thu

**Comment by AdrianValdes** [comment]
I am getting this error, I have tried to find a solution but I haven'T been able to do it.

> yarn add v1.22.10
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/eslint-config-small-ads: Not found".

**Comment by paschalidi** [comment]
Wait before you merge this. I am checking it

**Comment by paschalidi** [comment]
can you try on your root directory to run 

```
yarn lerna add styled-components --scope @small-ads/webapp  
```

**Comment by AdrianValdes** [comment]
That worked

**Comment by AdrianValdes** [comment]
BTW, Should I merge in the mean time? Are thing working on your side locally?

**Comment by paschalidi** [comment]
yep that works for me. lets merge it

**Comment by paschalidi** [comment]
https://github.com/lerna/lerna/issues/1886
There is an open issue for this on lerna. To remove the way you suggested you will be having to do what the person who posted the issue says they do.

**Pull request merged**
