### PR TITLE
chore: make `typescript` a devDependency

### PR DESCRIPTION
**Pull request by AdrianValdes**
hi @paschalidi,
Even though the issue says

> Make typescript devDependency in all the repos we have

I didn't do it on @small-ads because I thought there we do need as a dependency. Am I wrong?
Sorry I ask, I am trying to get see what parts of how the process works I am missing.

### CODE REVIEW

**Comment by AdrianValdes** [comment]
hi @paschalidi, 
Even though the issue says 

> Make typescript devDependency in all the repos we have

 I didn't do it on `@small-ads` because I thought there we do need as a dependency. Am I wrong?

**Review by paschalidi — COMMENTED** [review]
Right, what about type like for instance `@types/styled-components` do these need to be dependencies?

**Comment by paschalidi** [comment]
> I didn't do it on @small-ads because I thought there we do need as a dependency. Am I wrong?

No need to be sorry for asking dude. You right for the eslint package we need typescript as dependency

**Comment by AdrianValdes** [comment]
I couldn't move some of them because the linter complains: 

> '@firebase/auth-types' should be listed in the project's dependencies, not devDependencies.

**Review by paschalidi — APPROVED** [review]
thanks looks good

**Pull request merged**
